### ISSUE TITLE
Build failed on Mac OS X 10.11.2 El Capitan with AttributeError: 'BuildContext' object has no attribute 'new_task_gen'

### ISSUE THREAD

**Issue by pinxue** [jackaudio/jack2#163]
With latest code cloned from github, main stream.

./waf configure   
passed

./waf build
Waf: Entering directory `/Users/pinxue/projects/tools/jack2/build'
make[1]: Entering directory `/Users/pinxue/projects/tools/jack2/build'
Traceback (most recent call last):
  File "/Users/pinxue/projects/tools/jack2/waflib/Scripting.py", line 157, in waf_entry_point
    run_commands()
  File "/Users/pinxue/projects/tools/jack2/waflib/Scripting.py", line 260, in run_commands
    ctx = run_command(cmd_name)
  File "/Users/pinxue/projects/tools/jack2/waflib/Scripting.py", line 243, in run_command
    ctx.execute()
  File "/Users/pinxue/projects/tools/jack2/waflib/Scripting.py", line 595, in execute
    return execute_method(self)
  File "/Users/pinxue/projects/tools/jack2/waflib/Build.py", line 246, in execute
    self.execute_build()
  File "/Users/pinxue/projects/tools/jack2/waflib/Build.py", line 259, in execute_build
    self.recurse([self.run_dir])
  File "/Users/pinxue/projects/tools/jack2/waflib/Context.py", line 304, in recurse
    user_function(self)
  File "/Users/pinxue/projects/tools/jack2/wscript", line 713, in build
    bld.recurse('macosx')
  File "/Users/pinxue/projects/tools/jack2/waflib/Context.py", line 304, in recurse
    user_function(self)
  File "/Users/pinxue/projects/tools/jack2/macosx/wscript", line 50, in build
    jackd = bld.new_task_gen('cxx', 'program')
AttributeError: 'BuildContext' object has no attribute 'new_task_gen'

**Comment by joshdekock** [comment]
```diff
diff --git a/macosx/wscript b/macosx/wscript
index ba92505..77ed832 100644
--- a/macosx/wscript
+++ b/macosx/wscript
@@ -2,7 +2,7 @@
 # encoding: utf-8

 def create_jack_driver_obj(bld, target, sources, uselib = None):
-    driver = bld.new_task_gen('cxx', 'shlib')
+    driver = bld('cxx', 'shlib')
     driver.features.append('cc')
     driver.env['shlib_PATTERN'] = 'jack_%s.so'
     driver.defines = ['HAVE_CONFIG_H','SERVER_SIDE']
@@ -16,7 +16,7 @@ def create_jack_driver_obj(bld, target, sources, uselib = None):
     return driver

 def create_jack_audio_driver_obj(bld, target, sources, uselib = None):
-    driver = bld.new_task_gen('cxx', 'shlib')
+    driver = bld('cxx', 'shlib')
     driver.features.append('cc')
     driver.env['shlib_PATTERN'] = 'jack_%s.so'
     driver.defines = 'HAVE_CONFIG_H'
@@ -31,7 +31,7 @@ def create_jack_audio_driver_obj(bld, target, sources, uselib = None):
     return driver

 def create_jack_midi_driver_obj(bld, target, sources, uselib = None):
-    driver = bld.new_task_gen('cxx', 'shlib')
+    driver = bld('cxx', 'shlib')
     driver.features.append('cc')
     driver.env['shlib_PATTERN'] = 'jack_%s.so'
     driver.defines = 'HAVE_CONFIG_H'
@@ -47,7 +47,7 @@ def create_jack_midi_driver_obj(bld, target, sources, uselib = None):

 def build(bld):
     if bld.env['BUILD_JACKD'] == True:
-       jackd = bld.new_task_gen('cxx', 'program')
+       jackd = bld('cxx', 'program')
        jackd.includes = ['.', '../macosx', '../posix', '../common', '../common/jack']
        jackd.defines = 'HAVE_CONFIG_H'
        jackd.source = ['../common/Jackdmp.cpp']
```
Try this patch

**Comment by lilrc** [comment]
@joshdekock, this looks good to me. I assume you have tested this. I will apply this as soon as I get confirmation that it works from @pinxue.

**Comment by joshdekock** [comment]
I have tested it, although the build still fails for me. That's because of something completely different though.

**Comment by lilrc** [comment]
Fixed in the waf-macosx-fixes branch, which will be merged when things start to work.

**Comment by lilrc** [comment]
There are still issues, I bet, but this is fixed.

**Comment by pinxue** [comment]
Still have issues. I modified two files:

 macosx/coremidi/JackCoreMidiUtil.h:25:#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
 macosx/JackMachThread.h:73:#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>

by removing base path of header file, compiling continued and stopped at next error:
In file included from ../macosx/coreaudio/JackCoreAudioDriver.cpp:30:
/Users/pinxue/projects/tools/jack2/common/JackAC3Encoder.h:24:10: fatal error: 'aften/aften.h' file not found
#include <aften/aften.h>

It seems the header file is missed when adding this lib:

10:jack2 pinxue$ find ./ -name '*aften*'
.//macosx/libaften_pcm.a
.//macosx/libaften_static.a

------------

10:jack2 pinxue$ git status
On branch waf-macosx-fixes
nothing to commit, working directory clean
10:jack2 pinxue$ git branch
  master
* waf-macosx-fixes
10:jack2 pinxue$ ./waf configure
Setting top to                           : /Users/pinxue/projects/tools/jack2
Setting out to                           : /Users/pinxue/projects/tools/jack2/build
Checking for 'clang++' (C++ compiler)    : /usr/bin/clang++
Checking for 'clang' (C compiler)        : /usr/bin/clang
MacOS X detected
Checking for program 'doxygen'           : /opt/local/bin/doxygen
Checking for program 'pkg-config'        : /opt/local/bin/pkg-config
Checking for 'alsa' >= 1.0.18            : not found
Checking for 'libffado' >= 1.999.17      : not found
Checking for 'libfreebob' >= 1.0.0       : not found
Checking for 'gtkIOStream' >= 1.4.0      : not found
Checking for 'eigen3' >= 3.1.2           : not found
Checking for 'portaudio-2.0' >= 19       : not found
Checking for header windows.h            : not found
Checking for header mmsystem.h           : no
Checking for 'celt' >= 0.11.0            : yes
Checking for 'opus' >= 0.9.0             : yes
Checking for header opus/opus_custom.h   : not found
Checking for 'samplerate' >= 0           : yes
Checking for 'sndfile' >= 0              : yes
Checking for library readline            : yes
Checking for header readline/readline.h  : yes
Checking for function ppoll              : not found

==================
JACK 1.9.11 svn revision will checked and eventually updated during build
Build with a maximum of 64 JACK clients
Build with a maximum of 768 ports per application
Install prefix                           :  /usr/local
Library directory                        :  /usr/local/lib
Drivers directory                        :  /usr/local/lib/jack
Build debuggable binaries                :  no
C compiler flags                         :  ['-Wall']
C++ compiler flags                       :  ['-Wall']
Linker flags                             :  []
Build with engine profiling              :  no
Build with 32/64 bits mixed mode         :  no
Build standard JACK (jackd)              :  yes
Build D-Bus JACK (jackdbus)              :  no
Autostart method                         :  classic
Build doxygen documentation              :  yes
Enable ALSA driver                       :  no
Enable FireWire driver (FFADO)           :  no
Enable FreeBob driver                    :  no
Enable IIO driver                        :  no
Enable Portaudio driver                  :  no
Enable WinMME driver                     :  no
Build with CELT                          :  yes
Build Opus netjack2                      :  no
Build with libsamplerate                 :  yes
Build with libsndfile                    :  yes
Build with readline                      :  yes

'configure' finished successfully (0.718s)
10:jack2 pinxue$ ./waf build
Waf: Entering directory `/Users/pinxue/projects/tools/jack2/build'
make[1]: Entering directory `/Users/pinxue/projects/tools/jack2/build'
[  3/240] Compiling common/Jackdmp.cpp
[  4/240] Compiling common/JackDummyDriver.cpp
[  5/240] Compiling common/JackLoopbackDriver.cpp
[  6/240] Compiling common/JackNetDriver.cpp
[  7/240] Compiling common/JackNetOneDriver.cpp
[  8/240] Compiling common/netjack.c
[  9/240] Compiling common/netjack_packet.c
[ 10/240] Compiling common/JackProxyDriver.cpp
[ 11/240] Compiling macosx/coreaudio/JackCoreAudioDriver.cpp
[ 12/240] Compiling macosx/coremidi/JackCoreMidiInputPort.cpp
In file included from ../common/JackDummyDriver.cpp:21:
In file included from /Users/pinxue/projects/tools/jack2/common/JackDummyDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackTimedDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackAudioDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackDriver.h:27:
In file included from /Users/pinxue/projects/tools/jack2/common/JackPlatformPlug.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackPlatformPlug_os.h:58:
/Users/pinxue/projects/tools/jack2/macosx/JackMachThread.h:73:10: fatal error: 'CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h' file not found
#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
         ^
1 error generated.

In file included from ../common/JackLoopbackDriver.cpp:22:
In file included from /Users/pinxue/projects/tools/jack2/common/JackLoopbackDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackAudioDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackDriver.h:27:
In file included from /Users/pinxue/projects/tools/jack2/common/JackPlatformPlug.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackPlatformPlug_os.h:58:
/Users/pinxue/projects/tools/jack2/macosx/JackMachThread.h:73:10: fatal error: 'CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h' file not found
#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
         ^
1 error generated.

In file included from <built-in>:332:
<command line>:27:9: warning: 'HAVE_OPUS' macro redefined [-Wmacro-redefined]
#define HAVE_OPUS 1
        ^
<command line>:13:9: note: previous definition is here
#define HAVE_OPUS 0
        ^
In file included from ../common/Jackdmp.cpp:34:
In file included from /Users/pinxue/projects/tools/jack2/common/JackConstants.h:24:
/Users/pinxue/projects/tools/jack2/build/config.h:20:9: warning: 'HAVE_OPUS' macro redefined [-Wmacro-redefined]
#define HAVE_OPUS 0
        ^
<command line>:27:9: note: previous definition is here
#define HAVE_OPUS 1
        ^
In file included from ../common/Jackdmp.cpp:35:
In file included from /Users/pinxue/projects/tools/jack2/common/JackPlatformPlug.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackPlatformPlug_os.h:58:
/Users/pinxue/projects/tools/jack2/macosx/JackMachThread.h:73:10: fatal error: 'CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h' file not found
#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
         ^
2 warnings and 1 error generated.

In file included from ../common/JackNetOneDriver.cpp:23:
In file included from /Users/pinxue/projects/tools/jack2/common/JackNetOneDriver.h:23:
In file included from /Users/pinxue/projects/tools/jack2/common/JackTimedDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackAudioDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackDriver.h:27:
In file included from /Users/pinxue/projects/tools/jack2/common/JackPlatformPlug.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackPlatformPlug_os.h:58:
/Users/pinxue/projects/tools/jack2/macosx/JackMachThread.h:73:10: fatal error: 'CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h' file not found
#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
         ^
1 error generated.

In file included from ../common/JackNetDriver.cpp:21:
In file included from /Users/pinxue/projects/tools/jack2/common/JackNetDriver.h:23:
In file included from /Users/pinxue/projects/tools/jack2/common/JackTimedDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackAudioDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackDriver.h:27:
In file included from /Users/pinxue/projects/tools/jack2/common/JackPlatformPlug.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackPlatformPlug_os.h:58:
/Users/pinxue/projects/tools/jack2/macosx/JackMachThread.h:73:10: fatal error: 'CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h' file not found
#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
         ^
1 error generated.

In file included from ../common/JackProxyDriver.cpp:23:
In file included from /Users/pinxue/projects/tools/jack2/common/JackLockedEngine.h:23:
In file included from /Users/pinxue/projects/tools/jack2/common/JackEngine.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackGraphManager.h:27:
In file included from /Users/pinxue/projects/tools/jack2/common/JackConnectionManager.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackActivationCount.h:23:
In file included from /Users/pinxue/projects/tools/jack2/common/JackPlatformPlug.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackPlatformPlug_os.h:58:
/Users/pinxue/projects/tools/jack2/macosx/JackMachThread.h:73:10: fatal error: 'CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h' file not found
#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
         ^
1 error generated.

In file included from <built-in>:332:
<command line>:27:9: warning: 'HAVE_OPUS' macro redefined [-Wmacro-redefined]
#define HAVE_OPUS 1
        ^
<command line>:13:9: note: previous definition is here
#define HAVE_OPUS 0
        ^
In file included from ../macosx/coremidi/JackCoreMidiInputPort.cpp:23:
In file included from ../macosx/coremidi/JackCoreMidiInputPort.h:23:
In file included from ../macosx/coremidi/JackCoreMidiPort.h:26:
In file included from /Users/pinxue/projects/tools/jack2/common/JackConstants.h:24:
/Users/pinxue/projects/tools/jack2/build/config.h:20:9: warning: 'HAVE_OPUS' macro redefined [-Wmacro-redefined]
#define HAVE_OPUS 0
        ^
<command line>:27:9: note: previous definition is here
#define HAVE_OPUS 1
        ^
In file included from ../macosx/coremidi/JackCoreMidiInputPort.cpp:23:
In file included from ../macosx/coremidi/JackCoreMidiInputPort.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackMidiAsyncQueue.h:23:
In file included from /Users/pinxue/projects/tools/jack2/common/JackMidiPort.h:26:
In file included from /Users/pinxue/projects/tools/jack2/common/JackPlatformPlug.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackPlatformPlug_os.h:58:
/Users/pinxue/projects/tools/jack2/macosx/JackMachThread.h:73:10: fatal error: 'CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h' file not found
#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
         ^
2 warnings and 1 error generated.

In file included from <built-in>:332:
<command line>:27:9: warning: 'HAVE_OPUS' macro redefined [-Wmacro-redefined]
#define HAVE_OPUS 1
        ^
<command line>:13:9: note: previous definition is here
#define HAVE_OPUS 0
        ^
In file included from ../macosx/coreaudio/JackCoreAudioDriver.cpp:20:
In file included from ../macosx/coreaudio/JackCoreAudioDriver.h:26:
In file included from /Users/pinxue/projects/tools/jack2/common/JackAudioDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackDriver.h:25:
In file included from /Users/pinxue/projects/tools/jack2/common/JackClientInterface.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackCompilerDeps.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackCompilerDeps_os.h:23:
In file included from /Users/pinxue/projects/tools/jack2/common/JackConstants.h:24:
/Users/pinxue/projects/tools/jack2/build/config.h:20:9: warning: 'HAVE_OPUS' macro redefined [-Wmacro-redefined]
#define HAVE_OPUS 0
        ^
<command line>:27:9: note: previous definition is here
#define HAVE_OPUS 1
        ^
In file included from ../macosx/coreaudio/JackCoreAudioDriver.cpp:20:
In file included from ../macosx/coreaudio/JackCoreAudioDriver.h:26:
In file included from /Users/pinxue/projects/tools/jack2/common/JackAudioDriver.h:24:
In file included from /Users/pinxue/projects/tools/jack2/common/JackDriver.h:27:
In file included from /Users/pinxue/projects/tools/jack2/common/JackPlatformPlug.h:23:
In file included from /Users/pinxue/projects/tools/jack2/macosx/JackPlatformPlug_os.h:58:
/Users/pinxue/projects/tools/jack2/macosx/JackMachThread.h:73:10: fatal error: 'CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h' file not found
#include <CoreServices/../Frameworks/CarbonCore.framework/Headers/MacTypes.h>
         ^
2 warnings and 1 error generated.

Waf: Leaving directory `/Users/pinxue/projects/tools/jack2/build'
Build failed
 -> task in 'dummy' failed (exit status 1):
	{task 4489860816: cxx JackDummyDriver.cpp -> JackDummyDriver.cpp.3.o}
['/usr/bin/clang++', '-Wall', '-fPIC', '-I/Users/pinxue/projects/tools/jack2/build', '-I/Users/pinxue/projects/tools/jack2', '-I/Users/pinxue/projects/tools/jack2/build/common', '-I/Users/pinxue/projects/tools/jack2/common', '-I/Users/pinxue/projects/tools/jack2/build/common/jack', '-I/Users/pinxue/projects/tools/jack2/common/jack', '-I/Users/pinxue/projects/tools/jack2/build/macosx', '-I/Users/pinxue/projects/tools/jack2/macosx', '-I/Users/pinxue/projects/tools/jack2/build/posix', '-I/Users/pinxue/projects/tools/jack2/posix', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '../common/JackDummyDriver.cpp', '-c', '-o', '/Users/pinxue/projects/tools/jack2/build/common/JackDummyDriver.cpp.3.o']
 -> task in 'loopback' failed (exit status 1):
	{task 4489860368: cxx JackLoopbackDriver.cpp -> JackLoopbackDriver.cpp.4.o}
['/usr/bin/clang++', '-Wall', '-fPIC', '-I/Users/pinxue/projects/tools/jack2/build', '-I/Users/pinxue/projects/tools/jack2', '-I/Users/pinxue/projects/tools/jack2/build/common', '-I/Users/pinxue/projects/tools/jack2/common', '-I/Users/pinxue/projects/tools/jack2/build/common/jack', '-I/Users/pinxue/projects/tools/jack2/common/jack', '-I/Users/pinxue/projects/tools/jack2/build/macosx', '-I/Users/pinxue/projects/tools/jack2/macosx', '-I/Users/pinxue/projects/tools/jack2/build/posix', '-I/Users/pinxue/projects/tools/jack2/posix', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '../common/JackLoopbackDriver.cpp', '-c', '-o', '/Users/pinxue/projects/tools/jack2/build/common/JackLoopbackDriver.cpp.4.o']
 -> task in 'jackd' failed (exit status 1):
	{task 4489860176: cxx Jackdmp.cpp -> Jackdmp.cpp.2.o}
['/usr/bin/clang++', '-Wall', '-I/Users/pinxue/projects/tools/jack2/build', '-I/Users/pinxue/projects/tools/jack2', '-I/Users/pinxue/projects/tools/jack2/build/common', '-I/Users/pinxue/projects/tools/jack2/common', '-I/Users/pinxue/projects/tools/jack2/build/common/jack', '-I/Users/pinxue/projects/tools/jack2/common/jack', '-I/Users/pinxue/projects/tools/jack2/build/macosx', '-I/Users/pinxue/projects/tools/jack2/macosx', '-I/Users/pinxue/projects/tools/jack2/build/posix', '-I/Users/pinxue/projects/tools/jack2/posix', '-I/opt/local/include', '-I/opt/local/include/opus', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '-DHAVE_CELT=1', '-DHAVE_OPUS=1', '../common/Jackdmp.cpp', '-c', '-o', '/Users/pinxue/projects/tools/jack2/build/common/Jackdmp.cpp.2.o']
 -> task in 'netone' failed (exit status 1):
	{task 4489861328: cxx JackNetOneDriver.cpp -> JackNetOneDriver.cpp.6.o}
['/usr/bin/clang++', '-Wall', '-fPIC', '-I/Users/pinxue/projects/tools/jack2/build', '-I/Users/pinxue/projects/tools/jack2', '-I/Users/pinxue/projects/tools/jack2/build/common', '-I/Users/pinxue/projects/tools/jack2/common', '-I/Users/pinxue/projects/tools/jack2/build/common/jack', '-I/Users/pinxue/projects/tools/jack2/common/jack', '-I/Users/pinxue/projects/tools/jack2/build/macosx', '-I/Users/pinxue/projects/tools/jack2/macosx', '-I/Users/pinxue/projects/tools/jack2/build/posix', '-I/Users/pinxue/projects/tools/jack2/posix', '-I/opt/local/include', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '-DHAVE_SAMPLERATE=1', '-DHAVE_CELT=1', '../common/JackNetOneDriver.cpp', '-c', '-o', '/Users/pinxue/projects/tools/jack2/build/common/JackNetOneDriver.cpp.6.o']
 -> task in 'net' failed (exit status 1):
	{task 4489861072: cxx JackNetDriver.cpp -> JackNetDriver.cpp.5.o}
['/usr/bin/clang++', '-Wall', '-fPIC', '-I/Users/pinxue/projects/tools/jack2/build', '-I/Users/pinxue/projects/tools/jack2', '-I/Users/pinxue/projects/tools/jack2/build/common', '-I/Users/pinxue/projects/tools/jack2/common', '-I/Users/pinxue/projects/tools/jack2/build/common/jack', '-I/Users/pinxue/projects/tools/jack2/common/jack', '-I/Users/pinxue/projects/tools/jack2/build/macosx', '-I/Users/pinxue/projects/tools/jack2/macosx', '-I/Users/pinxue/projects/tools/jack2/build/posix', '-I/Users/pinxue/projects/tools/jack2/posix', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '../common/JackNetDriver.cpp', '-c', '-o', '/Users/pinxue/projects/tools/jack2/build/common/JackNetDriver.cpp.5.o']
 -> task in 'proxy' failed (exit status 1):
	{task 4489862096: cxx JackProxyDriver.cpp -> JackProxyDriver.cpp.7.o}
['/usr/bin/clang++', '-Wall', '-fPIC', '-I/Users/pinxue/projects/tools/jack2/build', '-I/Users/pinxue/projects/tools/jack2', '-I/Users/pinxue/projects/tools/jack2/build/common', '-I/Users/pinxue/projects/tools/jack2/common', '-I/Users/pinxue/projects/tools/jack2/build/common/jack', '-I/Users/pinxue/projects/tools/jack2/common/jack', '-I/Users/pinxue/projects/tools/jack2/build/macosx', '-I/Users/pinxue/projects/tools/jack2/macosx', '-I/Users/pinxue/projects/tools/jack2/build/posix', '-I/Users/pinxue/projects/tools/jack2/posix', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '../common/JackProxyDriver.cpp', '-c', '-o', '/Users/pinxue/projects/tools/jack2/build/common/JackProxyDriver.cpp.7.o']
 -> task in 'coremidi' failed (exit status 1):
	{task 4489862544: cxx JackCoreMidiInputPort.cpp -> JackCoreMidiInputPort.cpp.9.o}
['/usr/bin/clang++', '-Wall', '-fPIC', '-I/Users/pinxue/projects/tools/jack2/build', '-I/Users/pinxue/projects/tools/jack2', '-I/Users/pinxue/projects/tools/jack2/build/common', '-I/Users/pinxue/projects/tools/jack2/common', '-I/Users/pinxue/projects/tools/jack2/build/common/jack', '-I/Users/pinxue/projects/tools/jack2/common/jack', '-I/Users/pinxue/projects/tools/jack2/build/macosx', '-I/Users/pinxue/projects/tools/jack2/macosx', '-I/Users/pinxue/projects/tools/jack2/build/posix', '-I/Users/pinxue/projects/tools/jack2/posix', '-I/opt/local/include', '-I/opt/local/include/opus', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '-DHAVE_CELT=1', '-DHAVE_OPUS=1', '../macosx/coremidi/JackCoreMidiInputPort.cpp', '-c', '-o', '/Users/pinxue/projects/tools/jack2/build/macosx/coremidi/JackCoreMidiInputPort.cpp.9.o']
 -> task in 'coreaudio' failed (exit status 1):
	{task 4489861904: cxx JackCoreAudioDriver.cpp -> JackCoreAudioDriver.cpp.8.o}
['/usr/bin/clang++', '-Wall', '-fPIC', '-I/Users/pinxue/projects/tools/jack2/build', '-I/Users/pinxue/projects/tools/jack2', '-I/Users/pinxue/projects/tools/jack2/build/common', '-I/Users/pinxue/projects/tools/jack2/common', '-I/Users/pinxue/projects/tools/jack2/build/common/jack', '-I/Users/pinxue/projects/tools/jack2/common/jack', '-I/Users/pinxue/projects/tools/jack2/build/macosx', '-I/Users/pinxue/projects/tools/jack2/macosx', '-I/Users/pinxue/projects/tools/jack2/build/posix', '-I/Users/pinxue/projects/tools/jack2/posix', '-I/opt/local/include', '-I/opt/local/include/opus', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '-DHAVE_CELT=1', '-DHAVE_OPUS=1', '../macosx/coreaudio/JackCoreAudioDriver.cpp', '-c', '-o', '/Users/pinxue/projects/tools/jack2/build/macosx/coreaudio/JackCoreAudioDriver.cpp.8.o']
10:jack2 pinxue$

**Comment by pinxue** [comment]
Then I pulled aften from sourceforge, add header files into macosx dir.

The build continued and stopped at next error:
10:jack2 pinxue$ ./waf build
Waf: Entering directory `/Users/pinxue/projects/tools/jack2/build'
make[1]: Entering directory `/Users/pinxue/projects/tools/jack2/build'
[  5/240] Linking build/jack_dummy.so
[  7/240] Linking build/jack_loopback.so
[  8/240] Compiling common/JackNetDriver.cpp
[ 12/240] Linking build/jack_netone.so
[ 14/240] Linking build/jack_proxy.so
[ 15/240] Compiling macosx/coreaudio/JackCoreAudioDriver.cpp
[ 17/240] Compiling macosx/coremidi/JackCoreMidiOutputPort.cpp
[ 18/240] Compiling macosx/coremidi/JackCoreMidiPhysicalInputPort.cpp
Undefined symbols for architecture x86_64:
  "_JackSleep", referenced from:
      Jack::JackProxyDriver::Initialize() in JackProxyDriver.cpp.7.o
  "Jack::JackDriver::Initialize()", referenced from:
      vtable for Jack::JackRestarterDriver in JackProxyDriver.cpp.7.o
  "Jack::JackDriver::StopSlaves()", referenced from:
      vtable for Jack::JackProxyDriver in JackProxyDriver.cpp.7.o
      vtable for Jack::JackRestarterDriver in JackProxyDriver.cpp.7.o
.... (skip the long list)

**Comment by pinxue** [comment]
I'm using Xcode Version 7.2 (7C68),  OS X 10.11.2, 

celt installed via MacPorts 2.3.4, alsa and libffado cannot be found.

**Comment by lilrc** [comment]
This is work in progress. See pull request #179. The opus issues are caused by #176, but can be worked around by giving waf --opus=no. #179 is highest priority right now and any clean fix for #176 would require renaming defines (and would possibly be blocked by the same reason as #145).
