### ISSUE TITLE
JackRouter selection doesn't stick in system prefs for OSX 10.10 (Yosemite)

### ISSUE THREAD

**Issue by briancline** [jackaudio/jack2#84]
Jack OSX works on OS X 10.10 (so does the updated installer addressing the previous 64-bit issue), but the JackRouter system output device doesn't seem to work when selected under System Preferences -> Sound -> Output. This manifests as the output selection not "sticking," so after selecting it, and either closing System Preferences or simply going back to its main screen then re-selecting Sound -> Output, the output device remains the same non-JackRouter output as it was previously set to.

Unfortunately this seems to prevent me from routing output from OS X apps that just the system's current default output for audio, like most browsers, iTunes, QuickTime, etc. In my case I'm unable to route audio from those applications to [StereoTool](http://stereotool.com/) on OSX 10.10.

There seems to be acknowledgement of this on the Jack OS X mailing list ([here](https://groups.yahoo.com/neo/groups/jackosx/conversations/topics/4336) and [here](https://groups.yahoo.com/neo/groups/jackosx/conversations/topics/4342)), but I couldn't find an open issue tracking it, so creating this in the hopes it can gain some traction.

Has anyone been able to dig in to this yet? Definitely willing to help where I can (including running test builds and/or compiling and trial/error work on a machine experiencing this problem).

Thanks!

**Comment by ridgerider** [comment]
+1, having the same problem...

**Comment by sreimers** [comment]
+1

**Comment by sletz** [comment]
Known issue, no technical solution for now.

**Comment by theodejong** [comment]
That's really a pity... it seems such a great program.

**Comment by mcoffin** [comment]
+1

**Comment by bladeworks** [comment]
+1

**Comment by smilingthax** [comment]
Even when selecting JackRouter (e.g.) in the Output tab of Sound Preferences, the "Settings for the selected device" below will not update, but retain their previous state -- e.g. My "Headphones" output has a balance control, but my HDMI output does not. If I first select Headphones and then JackRouter, the balance control stays there. But if I first select HDMI and then switch to JackRouter, the message "The selected device has no output controls" stays, instead.

To me, this looks like Yosemite is querying JackRouter for some (additional) properties that JackRouter does not provide (or stumbles across some returned value, maybe SamplingRate==0?, cf. System Information > Audio) and then fails silently...

AFAICS, the most recent source code of JackRouter2 is still only availabe via CVS from sourceforge?
( http://jackosx.cvs.sourceforge.net/viewvc/jackosx/jackosx/jackrouter2/ )

Enabling JAR_fDebug in Sources/JARlog.c seems promising to get an idea of the problem, but where will the debug output then go to?

**Comment by pulsation** [comment]
+1

**Comment by ryanmeisters** [comment]
using soundflower as system output and JackRouter as soundflower output as a workaround.

**Comment by benklop** [comment]
where is the source for the JackRouter plugin?

**Comment by octabaka** [comment]
+1

**Comment by kevinwheeler** [comment]
+1

**Comment by ridgerider** [comment]
Has anyone tried if this is fixed with Osx El Capitan?.. I would really want this to be working but I am too unskilled to do anything myself...

**Comment by sletz** [comment]
It won't be fixed by "magic" I guess�

Le 16 sept. 2015 � 22:26, ridgerider <notifications@github.com> a �crit :

**Comment by briancline** [comment]
@smilingthax, the debug output will likely be sent to /var/log/system.log (one of the logs Console.app tails by default). I may give your suggestion a shot and see if the output yields anything useful. Hopefully it won't be too troublesome to compile under 10.10.5 and Xcode 7.

I created a git copy of the cvs repo here (history preserved):
https://github.com/briancline/jackosx/

**Comment by benschmaus** [comment]
@briancline any luck debugging the issue on yosemite?

**Comment by OrangeK** [comment]
I can't find an option to select JackRouter is Sound settings anywhere either

**Comment by OrangeK** [comment]
Not in System Preferences or in Audio MIDI Setup. It's just gone.
![screen shot 2015-11-14 at 6 57 58 pm](https://cloud.githubusercontent.com/assets/10160927/11166951/c7d01b7e-8b01-11e5-82dc-6b53d2eebe07.png)
![screen shot 2015-11-14 at 6 58 17 pm](https://cloud.githubusercontent.com/assets/10160927/11166952/c80a3a48-8b01-11e5-8444-c0f7b2ab10b0.png)
![screen shot 2015-11-14 at 6 58 24 pm](https://cloud.githubusercontent.com/assets/10160927/11166953/c80acf76-8b01-11e5-8527-97b86d0f38ae.png)

**Comment by setrar** [comment]
Has this issue been ported to El Captain?

I am running Yosemite on a laptop and it looks like it has been resolved.

![screen shot 2015-12-13 at 1 13 05 pm](https://cloud.githubusercontent.com/assets/123704/11768465/82bf883e-a19b-11e5-8efd-5053d454a306.png)

**Comment by OrangeK** [comment]
I'll have to see

**Comment by cfillion** [comment]
I'm still having this issue on Yosemite. JackRouter cannot be selected as part of an Aggregate Device or Multi-Output Device (it isn't in the list...).

https://i.imgur.com/kfAB9sE.png

**Comment by forkclinic** [comment]
Hi, I updated to El Capitan and it was working, but a few days ago started to have problems, apps couldn't detect Jack and viceversa. I decided to uninstall it and install it again, but now I can't, it tells me the latest version is not compatible with El Capitan, any suggestions?

**Comment by rsparkyc** [comment]
As of now, I'm assuming we'll need to resort to using soundflower for system audio?

**Comment by mk-conn** [comment]
Still an issue... isn't it?

**Comment by JDLH** [comment]
+1 on OS X El Capitan, version 10.11.6

**Comment by keybounce** [comment]
> using soundflower as system output and JackRouter as soundflower output as a workaround.

Doesn't this make the output all seem to come from one application? Which would make QJackCtl useless for the goal of sending different program audio out to different devices.

**Comment by storix** [comment]
macOS Sierra, still having the same issue (jackOSX Version 0.92_b3)

**Comment by sletz** [comment]
Known issue, no technical solution for now.

**Comment by denschub** [comment]
Y'all are aware that jackOSX 0.92_b3 is from May 2014 and hasn't received any updates since then? Also, that the sources in the `macos` folder are equally old, if not older? This is likely a dead platform for the jack team. ;)

**Comment by duck57** [comment]
@denschub What alternate software should I use to keep the same functionality?

**Comment by kmatheussen** [comment]
@denschub I think all of what you wrote is wrong. 0.92_b3 is from last year or thereabout (not 2014), jack for osx is still being maintained, last update in the macos folder was 6 months ago (not 2014), and jack is still being developed, of course.

**Comment by denschub** [comment]
@kmatheussen, with all due respect, you are wrong.

First, note that my previous comment was made in October, when [this commit](https://github.com/jackaudio/jackaudio.github.com/commit/f2b92194ec8c248aa60d69c579827bc162bdb5f8) was not yet visible on the public site, and [the previous version](https://github.com/jackaudio/jackaudio.github.com/commit/24076c3d1fc54fb4b96ea007ab455e8fe4dfaf79) was indeed from 2014. If you have a look at [the actual file history](https://github.com/jackaudio/jack2/tree/master/macosx) inside the macosx folder, the only changes that happened since 2015 are changes to ` 	Jack-Info.plist`, and those are just increments of the version number, with absolutely no change to the actual sources.

That, besides the fact that Jack for OSX is **unusable** for everyone since macOS 10.10 (released in 2014), the issue being acknowledged in this very thread [three years ago](https://github.com/jackaudio/jack2/issues/84#issuecomment-69199998), and the fact that there has been absolutely zero endeavors on anything macOS related leads me to the conclusion that macOS is indeed a dead platform for the jack team.

And that's all I claimed. I never claimed that jack itself was a dead project, because it isn't. But please don't act like you are maintaining jack for osx, when the opposite is a simple fact. And things don't get easier for former users if you do claim so. People are apparently still stumbling around this issue in the hope to find a solution that is not soundflower, but I feel like this project is at a point where macOS support should officially be declared dead.

But whatever, these are just my two cents.

**Comment by falkTX** [comment]
JACK still works fine on macOS afaik, only the JackRouter functionality does not.
Is that wrong?

**Comment by denschub** [comment]
You cannot select it as an audio device, so what is "works" by your definition? You cannot select it as audio device, nor can you route audio to it by manually selecting it as an audio device programmatically by hard-coding the audio device in your sources, sooo... I mean, the daemon technically runs fine, yes. But when you can't send audio to or receive audio from, it's kinda useless.

**Comment by kmatheussen** [comment]
@denschub As far as I can see, I wasn't wrong about anything. There's been lots of commits in the macosx directory since 2014: https://github.com/jackaudio/jack2/commits/master/macosx
Also please don't write that jack hasn't worked since macOS 10.10, when you actually only think about the JackRouter. That's more misinformation.

**Comment by denschub** [comment]
As I said, if your definition of *working* is having the jack deamon running to handle audio sent to jack directly, then yes, it is working. I can't think of any use case for that on macOS, as I am not aware of any osx application actually routing audio to jack. There might be a few cases with cross-compiled linux applications, but most of the ones I just checked either route audio directly or don't compile because of other platform dependencies. So while there may be a very small gap for use cases here, given the amount of reactions here and in other channels, I assume this is not the main use case when people install jack under macOS.

Since we apparently have different definitions of "working" (which is fine), I'll clarify my communication whenever I talk about Jack on macOS in the future.

> There's been lots of commits in the macosx directory since 2014

The last commit that actually changed sources were done in https://github.com/jackaudio/jack2/commit/7cb81394ece172ccefdee328ca6b53d6a46e24af, which is a commit from 2015. If we are really generous, we could include https://github.com/jackaudio/jack2/commit/02f74a659aeb7120dfd462a7e24c9628f28f842d, which would be a commit from 2016, but this looks like a global search/replace action and the resulting changes to (auto generated) build files, probably caused by running the xcode-compiler. All other commits are literally just changes to build meta files. 

The discussion about whether there were changes to the macOS specific sources or not is actually totally pointless, but you alleging me of spreading misinformation, even though everyone can simply verify my claims, is offending me. I'll stop participating from this point on.

Sorry for the noise in everyone's inbox.

**Comment by JDLH** [comment]
@kmatheussen , @denschub Please note that this is a bug report about JackRouter. The title is, "JackRouter selection doesn't stick in system prefs for OSX 10.10 (Yosemite)". Discussions of the Jack project in general are interesting and important, but perhaps not here. @kmatheussen , if you know of any activity which might address _this JackRouter issue_, please let us know. 

Personally, my interest in Jack was entirely for JackRouter's potential as a way of routing audio signals between Mac apps that are not written specially to use Jack.  From what I see in this issue's discussion, @denschub 's description seems pretty fair. JackRouter was reported not working in Dec 2014 on Mac OS 10.10, many people confirmed this in subsequent years and subsequent OS version, including me in Oct 2017 on Mac OS 10.11. No-one has reported developer team activity to reproduce this issue or to fix it. If Jack is not a dead platform for the Jack team, this issue is not proving it to be alive.

**Comment by falkTX** [comment]
I do not want to deviate the issue too much but I feel like I should say that, as one of the current jack2 maintainers, the macOS platform has very little interest to me.
In Linux we can already do what you say - route audio from one application to another, which is what I use on a daily basis. Perhaps if I used macOS daily, I'd care about this specific issue too.

As it is, someone who is skilled enough has to come up with an alternative solution for this that still works with the latest Apple change/breakages. And be willing to keep it updated once more breaking changes happen again and code needs to be rewritten.

There was one project that showed promise, though I did not look at it yet.
Once I am done with DISTRHO, DPF and KXStudio releases, I'll dedicate time to JACK development. By then I will take a look at this myself, but if it's a big amount of work (and research) the issue will just be unfixed (that is, JackRouter removed)

**Comment by JDLH** [comment]
@falkTX Thank you for speaking as a jack2 maintainer. And thank you for the work you put into jack2. I appreciate that you are contributing software for the rest of us to use at no charge.

That said, I think it boils down to Mac OS X being a dead platform (at least for the JackRouter feature) unless a developer steps forward with an interest in Mac. That's useful expectation-setting for this issue.

**Comment by sletz** [comment]
"You cannot select it as an audio device," : since 10.9:

- JackRouter can still be used by applications that can **explicitly** select an audio device. 

- JackRouter cannot be used as the **default** audio device, so cannot be used anymore by applications (like iTunes..) that can only use the system configurated  default audio device

This has already been explained over and over on different places...

**Comment by keybounce** [comment]
> I do not want to deviate the issue too much but I feel like I should say that, as one of the current jack2 maintainers, the macOS platform has very little interest to me.
> In Linux we can already do what you say - route audio from one application to another, which is what I use on a daily basis. Perhaps if I used macOS daily, I'd care about this specific issue too.

The problem is twofold. First, because virtually every game uses default audio output, this fails with Jack past 10.9. On anything past 10.9, I can do this with a complicated combination of a multiple audio out device, several SoundFlowers, a large combination device, and even then I get all (system) audio output as opposed to only the game's audio output.

Second, if an application allows me to specify a device, I can already send it to an appropriate combination device (again, multi-audio device and multi-output device, with the same SoundFlowers linked on both of them), so it is only the default output jack router that matters in Jack.
