### ISSUE TITLE
Jack stops when I press notes on my midi keyboard? (I don't even use it for midi)

### ISSUE THREAD

**Issue by gsirvine** [jackaudio/jack2#986]
## Describe the bug

Jack stops when I press notes on my midi keyboard? (I don't even use jack for midi nor do I see any midi settings in jack)

## Environment

* **JACK Version:** ![image](https://github.com/user-attachments/assets/844ee178-0655-4acb-836f-17bb48e2dbb4)
* **Operating System:** Windows 10
* **Installation:** downloaded from the website https://jackaudio.org/downloads/

## Steps To Reproduce

Press note on midi keyboard > jack stops (doesn't crash just stops)

Video of the steps. 
https://github.com/user-attachments/assets/c7c8545a-5bfb-4430-9009-db91edbbd395

Message output
```bash
18:29:50.845 JACK connection graph change.
Allocate: named semaphore already exist name = jack_pipe.default_qjackctl
18:30:34.690 Shutdown notification.
18:30:34.695 Client deactivated.
18:30:34.705 JACK is being forced...
18:30:34.906 JACK was stopped
```

Jack setup:
I have jack set to my asio driver. I don't even understand why it reacts to midi. I don't want it to.
![image](https://github.com/user-attachments/assets/11c70b06-9907-4156-9000-5abed7524d09)

### Expected vs. actual behavior

It keeps running when i press midi notes would be my expected behavior. It makes no sense because I see no settings that relate to midi. I wish I could just turn everything midi related off for jack.

**Comment by gsirvine** [comment]
:'(

**Comment by gsirvine** [comment]
Okay I unplugged my midi controller from the direct USB port connection and plugged it's usb cable into a midi interface that has it's own usb host port on it. This somehow works around the issue. 

There is some sort of interaction between direct midi over USB and jack or it is specifically an issue with this midi controller (the roli seaboard). 

Either way this works around the issue. (Sorta)

Downside to this is the whole reason for having an MPE controller is that you can use MPE. (Multi timbral polyphonic expression or Midi polyphonic expression). 

By going through this controller I don't know if it can pass MPE. Just plain old midi notes. Sucks kind of. I will play around with settings a bit and see if I can get it to pass MPE.


What could  be causing an interaction for this? Direct USB connection causing jack to turn off on midi notes being pressed?

**Comment by dimm-soft** [comment]
I also encountered this problem. So far I have managed to simply disable MIDI by deleting the launch line argument `-X winmme`

**Comment by falkTX** [comment]
This was already fixed in latest develop branch, but I still need to make a new release with the fix.
If you want test a new build that has the fix you can use the latest available build
https://github.com/jackaudio/jack2/actions/runs/9828548183/artifacts/1681291121

**Comment by pljones** [comment]
Ah!  I was about to report this.  I'll grab the Windows build and give it a go.

**Comment by pljones** [comment]
OK, that looks good:
```
Jack: JackWinMMEInputPort::EnqueueMessage - enqueueing event at 1579984.313000 (frame: 5772455) with start offset '57738' scheduled for frame '5772490'
Jack: JackWinMMEInputPort::EnqueueMessage - enqueueing event at 1580122.771000 (frame: 5786173) with start offset '57877' scheduled for frame '5786263'
```
whereas it would have just done the `JACK is being forced...`, `JACK was stopped` thing.

**Comment by Krisbruijn1** [comment]
Any solutions for this issue?

**Comment by pljones** [comment]
> Any solutions for this issue?

See https://github.com/jackaudio/jack2/issues/986#issuecomment-2382384936

**Comment by gsirvine** [comment]
did this fix make it into the final? the version number is the same as when i checked last

> This was already fixed in latest develop branch, but I still need to make a new release with the fix. If you want test a new build that has the fix you can use the latest available build https://github.com/jackaudio/jack2/actions/runs/9828548183/artifacts/1681291121

**Comment by gsirvine** [comment]
> OK, that looks good:
> 
> ```
> Jack: JackWinMMEInputPort::EnqueueMessage - enqueueing event at 1579984.313000 (frame: 5772455) with start offset '57738' scheduled for frame '5772490'
> Jack: JackWinMMEInputPort::EnqueueMessage - enqueueing event at 1580122.771000 (frame: 5786173) with start offset '57877' scheduled for frame '5786263'
> ```
> 
> whereas it would have just done the `JACK is being forced...`, `JACK was stopped` thing.

link is dead

**Comment by gsirvine** [comment]
> > Any solutions for this issue?
> 
> See [#986 (comment)](https://github.com/jackaudio/jack2/issues/986#issuecomment-2382384936)

"This was already fixed in latest develop branch, but I still need to make a new release with the fix.
If you want test a new build that has the fix you can use the latest available build
https://github.com/jackaudio/jack2/actions/runs/9828548183/artifacts/1681291121"

link is dead
@falkTX 


I'm guessing it is probably part of the nightly.

What I did was this as a workaround. Actually this is the solution for anyone who never wants to do midi. I never want Jack to do midi. So i did what was suggested above.

**Workaround if you must stay on 1.9.22**
• Disable the Windows MIDI backend so JACK ignores WinMME: 

**remove -X winmme from the JACK server command** 

**(QjackCtl → Setup → Settings → Advanced → Server Prefix). That flag is what enables WinMME MIDI on Windows.**

I have no interest in Jack midi whatsoever so this works.

**Comment by chiaccona** [comment]
Any hope of getting an updated Win64 release that includes this fix?  1.9.22 predates the fix and still crashes, so MIDI doesn't work.
